# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='r',
            new_name='radianos',
        ),
    ]
